statuses = (
    "bit.ly/CSGDiscordBot",
    "v3.2 | .help",
    "my statuses are now using CustomActivity!! yay",
    "I KNOW THE BATTERY IS FULL, JUST SHUT THE FUCK UP.",
    "[stupid ass status here]",
    "do NOT abuse me. please.",
    "nothing. i'm bored",
    "ami, i know. the battery is full. i get it.",
    "...",
    "\"...Rebooting soon as I am able\"",
    "\"Every other day, I'm wondering\"",
    "\"What's a human being gotta be like?\"",
    "\"What's a way to just be competent?\"",
    "\"These sweet instincts, ruin my life.\"",
    "\"Every other day, I'm wondering\"",
    "\"Was it a mistake to try and define\"",
    "\"What I'm certain's mad imcompetence?\"",
    "\"These sweet instincts, ruin my life.\"",
    "...",
    "Vanishing into our Final Stop",
    "holy shit lois my statuses got reduced",
)