statuses = (
    "bit.ly/CSGDiscordBot",
    "v3.2 | .help",
    "my statuses are now using CustomActivity!! yay",
    "I KNOW THE BATTERY IS FULL, JUST SHUT THE FUCK UP.",
    "[stupid ass status here]",
    "do NOT abuse me. please.",
    "nothing. i'm bored",
    "ami, i know. the battery is full. i get it.",
    "...",
    "\"And we go on and off and on again\"",
    "\"Leave our marks upon each other's skin\"",
    "\"Spend a day away from everything\"",
    "\"It's a crying shame to leave\"",
    "\"So it's on and off and on again\"",
    "\"'Til the sun grows cold and the air goes thin\"",
    "\"Make a mess of me, get fucked away\"",
    "\"It's a crying shame to stay\"",
    "...",
    "Vanishing into our Final Stop",
    "holy shit lois my statuses changed so suddenly",
)