statuses = (
    "bit.ly/CSGDiscordBot",
    "v3.2 | .help",
    "my statuses are now using CustomActivity!! yay",
    "I KNOW THE BATTERY IS FULL, JUST SHUT THE FUCK UP.",
    "[stupid ass status here]",
    "do NOT abuse me. please.",
    "nothing. i'm bored",
    "ami, i know. the battery is full. i get it.",
    "...",
    "\"Falling like a drop from cloud to cheek\"",
    "\"Oh, I'll live in parallel with all my dreams\"",
    "\"I give in to the noise and finally see\"",
    "\"I've been singing to a crowd who all feel just like me\"",
    "\"I want it to be true\"",
    "\"'I wanna be just like you\"",
    "\"I'd do anything to make you proud one day\"",
    "\"I'll be your steadfast protégé\"",
    "...",
    "Vanishing into our Final Stop",
    "holy shit lois my statuses changed so suddenly",
)